### ISSUE TITLE
Variational autoencoder error (ruta)

### ISSUE THREAD

**Issue by harikiyer** [fdavidcl/ruta#43]
I tried to run the code for VAE - just copy pasting in RStudio - and I got the following error when executing the following command.

model <- learner %>% train(x_train, epochs = 5)

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  _SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'z_mean_3/Identity:0' shape=(None, 3) dtype=float32>, <tf.Tensor 'z_log_var_3/Identity:0' shape=(None, 3) dtype=float32>] 

Any clue on what I am doing wrong? Thanks.

PS: Figured out from more reading.   Needed the following lines:
if (tensorflow::tf$executing_eagerly())
  tensorflow::tf$compat$v1$disable_eager_execution()

Working now.

Thanks.

**Comment by fdavidcl** [comment]
Thanks for the heads up! It looks like they updated `tensorflow` to use eager execution by default. Will have to document this somewhere then.

**Comment by harikiyer** [comment]
Thank you for sharing the code. Very helpful in my learning process.
